// <auto-generated/>

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProduct("Octokit")]
[assembly: AssemblyVersion("0.14.0")]
[assembly: AssemblyFileVersion("0.14.0")]
[assembly: ComVisible(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.14.0";
    }
}
