// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("Octokit")]
[assembly: AssemblyVersionAttribute("0.4.1")]
[assembly: AssemblyFileVersionAttribute("0.4.1")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.4.1";
    }
}
