name: Links (Fail Fast)

on:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.1
        with:
          fail: true
          args: --max-redirects 0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
