name:  Local NuGet

on:
  workflow_dispatch:
  push:
    branches:
      - local
      
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet 
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
          source-url: https://nuget.pkg.github.com/dirtygooback/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build
        run: dotnet build
        
      - name: Pack
        run: dotnet pack -c Release -o out
          
      - name: Build solution and generate NuGet package
        run: dotnet nuget list source          
         
      - name: Push generated package to GitHub registry
        run: dotnet nuget push "${GITHUB_WORKSPACE}/out/Octokit.3.*.nupkg"
        
